'use strict';
const assert = require('node:assert/strict');
const { endpoint, validateFeed, parseLines, nxLink } = require('../yookds-for-woocommerce/assets/js/kds.js');
const receipt = require('../yookds-for-woocommerce/assets/js/receipt-numbers.js');
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
test('normal REST URL',()=>assert.equal(endpoint('https://shop.test/wp-json/yookds/v1/', 'orders'), 'https://shop.test/wp-json/yookds/v1/orders'));
test('subdirectory REST URL',()=>assert.equal(endpoint('https://shop.test/store/wp-json/yookds/v1/', 'orders/12/actions'), 'https://shop.test/store/wp-json/yookds/v1/orders/12/actions'));
const plain = new URL(endpoint('https://shop.test/?rest_route=/yookds/v1/', 'archive', { q: 'vitlök & #12', page: 2 }));
test('plain permalink route retained',()=>assert.equal(plain.searchParams.get('rest_route'), '/yookds/v1/archive'));
test('search special characters roundtrip',()=>assert.equal(plain.searchParams.get('q'), 'vitlök & #12'));
test('page parameter retained',()=>assert.equal(plain.searchParams.get('page'), '2'));
const boot={site:'https://shop.test/',version:'1.1.0-alpha.2',settings:{receive_statuses:['processing','pending','on-hold']}};
const token='a'.repeat(32);
const order={id:27080,order_number:'7080',revision:1,token:'abc',items:[{details:[]}],shipping:[],woo_status:'processing',state:'preparing'};
const feed=()=>({source:'woocommerce',schema:2,site:boot.site,version:boot.version,read_id:token,orders:[structuredClone(order)],server_time:12345});
const valid=data=>validateFeed(data,boot,token,true);
test('genuine contract accepted',()=>assert.equal(valid(feed())[0].id,27080));
test('empty response stays empty',()=>assert.deepEqual(valid({...feed(),orders:[]}),[]));
for(const [key,value] of Object.entries({source:'demo',schema:1,site:'https://other.test/',version:'1.1.0-alpha.1',read_id:'old'}))test('reject mismatched '+key,()=>assert.throws(()=>valid({...feed(),[key]:value})));
for(const status of ['completed','cancelled','failed','refunded','checkout-draft'])test('reject active '+status,()=>{const d=feed();d.orders[0].woo_status=status;assert.throws(()=>valid(d));});
test('reject duplicate full IDs',()=>assert.throws(()=>valid({...feed(),orders:[order,order]})));
test('short numbers can collide without collapsing identities',()=>{const d=feed();d.orders.push({...order,id:37080});assert.equal(valid(d).length,2);});
test('reject short display number used as string ID',()=>{const d=feed();d.orders[0].id='7080';assert.throws(()=>valid(d));});
test('reject missing items',()=>{const d=feed();delete d.orders[0].items;assert.throws(()=>valid(d));});
test('reject missing options structure',()=>{const d=feed();d.orders[0].items=[{name:'x'}];assert.throws(()=>valid(d));});
test('archived real order can be shown only in history',()=>{const d=feed();d.orders[0].state='archived';d.orders[0].woo_status='completed';assert.equal(validateFeed(d,boot,token,false).length,1);});
test('custom fields line parser',()=>assert.deepEqual(parseLines('order|_delivery_time|Leveranstid\nitem|extra|Extra', ['scope','key','label']),[{scope:'order',key:'_delivery_time',label:'Leveranstid'},{scope:'item',key:'extra',label:'Extra'}]));
test('blank custom fields means none',()=>assert.deepEqual(parseLines(' \n ',['scope','key','label']),[]));
test('reject incomplete custom field line',()=>assert.throws(()=>parseLines('order|_x',['scope','key','label'])));
test('NX preserves menu query and fragment',()=>{const u=new URL(nxLink('https://shop.test/meny/?lang=sv#food',{table:'18',station:'1',channel:'table'}));assert.equal(u.searchParams.get('lang'),'sv');assert.equal(u.hash,'#food');assert.equal(u.searchParams.get('nx_table'),'18');assert.equal(u.searchParams.get('nx_station'),'1');});
test('NX table infers QR channel',()=>assert.equal(new URL(nxLink('https://shop.test',{table:'18'})).searchParams.get('nx_channel'),'table'));
test('NX removing old table from link',()=>assert.equal(new URL(nxLink('https://shop.test/?nx_table=7',{channel:'web'})).searchParams.has('nx_table'),false));
test('NX invalid URL scheme rejected',()=>assert.throws(()=>nxLink('javascript:alert(1)',{})));
for(const [input,expected] of [['#27080','#7080'],['7','#0007'],['0000','#0000'],['12345','#2345'],['abc','']])test('receipt display '+input,()=>assert.equal(receipt.format(input),expected));
test('external and Woo numeric IDs remain separate',()=>{const d=feed();d.orders.push({...order,id:-27080,kind:'external',provider:'wolt'});assert.equal(valid(d).length,2);});
test('negative ID requires known external provider',()=>{const d=feed();d.orders[0].id=-1;assert.throws(()=>valid(d));});
test('external tickets independent of Woo receive status selection',()=>{const d=feed();d.orders=[{...order,id:-1,kind:'external',provider:'foodora'}];assert.equal(validateFeed(d,{...boot,settings:{receive_statuses:['on-hold']}},token,true).length,1);});
console.log('\n'+count+' JavaScript checks passed.');
